### ISSUE TITLE
Many errors logs should to be ignored

### ISSUE THREAD

**Issue by zjg555543** [0xPolygon/zkevm-data-streamer#151]
## version
While useing Erigon rpc([v2.60.0-beta5](https://github.com/0xPolygonHermez/cdk-erigon/releases/tag/v2.60.0-beta5)) to connect data stream([v0.2.7](https://github.com/0xPolygon/zkevm-data-streamer/tree/v0.2.7)).

## issue
The rpc node always connect and stop the data stream by a single call.
https://github.com/0xPolygonHermez/cdk-erigon/blob/v2.60.0-beta5/zk/stages/stage_batches.go#L194

So, here is the data streamer's error logs. I think we can ignore this. 
Hope to help.
## data stream logs
```
xlayer-ds               | 2024-11-08T10:15:22.095Z	ERROR	datastreamer/streamserver.go:829	Stream to client already stopped!	{"pid": 1, "version": "v0.1.0"}
xlayer-ds               | github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).handleStopCommand
xlayer-ds               | 	/src/datastreamer/streamserver.go:829
xlayer-ds               | github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).processCommand
xlayer-ds               | 	/src/datastreamer/streamserver.go:772
xlayer-ds               | github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).handleConnection
xlayer-ds               | 	/src/datastreamer/streamserver.go:341
xlayer-ds               | 2024-11-08T10:15:22.095Z	ERROR	datastreamer/streamserver.go:343	Error processing command 2[Stop] from 192.168.80.16:51266: client already stopped%!(EXTRA string=
xlayer-ds               | /src/log/log.go:145 github.com/0xPolygonHermez/zkevm-data-streamer/log.appendStackTraceMaybeArgs()
xlayer-ds               | /src/log/log.go:254 github.com/0xPolygonHermez/zkevm-data-streamer/log.Errorf()
xlayer-ds               | /src/datastreamer/streamserver.go:343 github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).handleConnection()
xlayer-ds               | )	{"pid": 1, "version": "v0.1.0"}
xlayer-ds               | github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).handleConnection
xlayer-ds               | 	/src/datastreamer/streamserver.go:343
xlayer-rpc              | [INFO] [11-08|10:15:22.098] zjg,Connecting to server xlayer-ds:7900 
xlayer-ds               | 2024-11-08T10:15:22.100Z	ERROR	datastreamer/streamserver.go:829	Stream to client already stopped!	{"pid": 1, "version": "v0.1.0"}
xlayer-ds               | github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).handleStopCommand
xlayer-ds               | 	/src/datastreamer/streamserver.go:829
xlayer-ds               | github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).processCommand
xlayer-ds               | 	/src/datastreamer/streamserver.go:772
xlayer-ds               | github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).handleConnection
xlayer-ds               | 	/src/datastreamer/streamserver.go:341
xlayer-ds               | 2024-11-08T10:15:22.100Z	ERROR	datastreamer/streamserver.go:343	Error processing command 2[Stop] from 192.168.80.16:51278: client already stopped%!(EXTRA string=
xlayer-ds               | /src/log/log.go:145 github.com/0xPolygonHermez/zkevm-data-streamer/log.appendStackTraceMaybeArgs()
xlayer-ds               | /src/log/log.go:254 github.com/0xPolygonHermez/zkevm-data-streamer/log.Errorf()
xlayer-ds               | /src/datastreamer/streamserver.go:343 github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).handleConnection()
xlayer-ds               | )	{"pid": 1, "version": "v0.1.0"}
xlayer-ds               | github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).handleConnection
xlayer-ds               | 	/src/datastreamer/streamserver.go:343
xlayer-rpc              | [INFO] [11-08|10:15:23.101] zjg,Connecting to server xlayer-ds:7900 
xlayer-ds               | 2024-11-08T10:15:23.103Z	ERROR	datastreamer/streamserver.go:829	Stream to client already stopped!	{"pid": 1, "version": "v0.1.0"}
xlayer-ds               | github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).handleStopCommand
xlayer-ds               | 	/src/datastreamer/streamserver.go:829
xlayer-ds               | github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).processCommand
xlayer-ds               | 	/src/datastreamer/streamserver.go:772
xlayer-ds               | github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).handleConnection
xlayer-ds               | 	/src/datastreamer/streamserver.go:341
xlayer-ds               | 2024-11-08T10:15:23.103Z	ERROR	datastreamer/streamserver.go:343	Error processing command 2[Stop] from 192.168.80.16:51282: client already stopped%!(EXTRA string=
xlayer-ds               | /src/log/log.go:145 github.com/0xPolygonHermez/zkevm-data-streamer/log.appendStackTraceMaybeArgs()
xlayer-ds               | /src/log/log.go:254 github.com/0xPolygonHermez/zkevm-data-streamer/log.Errorf()
xlayer-ds               | /src/datastreamer/streamserver.go:343 github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).handleConnection()
xlayer-ds               | )	{"pid": 1, "version": "v0.1.0"}
xlayer-ds               | github.com/0xPolygonHermez/zkevm-data-streamer/datastreamer.(*StreamServer).handleConnection
```

## erigon rpc stacks
```
xlayer-rpc              | goroutine 145 [running, locked to thread]:
xlayer-rpc              | runtime/debug.Stack()
xlayer-rpc              | 	runtime/debug/stack.go:24 +0x5e
xlayer-rpc              | runtime/debug.PrintStack()
xlayer-rpc              | 	runtime/debug/stack.go:16 +0x13
xlayer-rpc              | github.com/ledgerwatch/erigon/zk/datastream/client.(*StreamClient).Stop(0xc001092900)
xlayer-rpc              | 	github.com/ledgerwatch/erigon/zk/datastream/client/stream_client.go:228 +0x27
xlayer-rpc              | github.com/ledgerwatch/erigon/zk/datastream/client.(*StreamClient).GetLatestL2Block(0xc001092900)
xlayer-rpc              | 	github.com/ledgerwatch/erigon/zk/datastream/client/stream_client.go:196 +0x26c
xlayer-rpc              | github.com/ledgerwatch/erigon/zk/stages.SpawnStageBatches(0xc001ace160, {0x2db93a8?, 0xc000db0420}, {0x2dc34d0, 0xc000c188c0}, {0x2dec820, 0xc000d30a80}, {{0x2dd3cb8, 0xc000c44900}, 0x0, ...})
xlayer-rpc              | 	github.com/ledgerwatch/erigon/zk/stages/stage_batches.go:179 +0xa33
xlayer-rpc              | github.com/ledgerwatch/erigon/zk/stages.DefaultZkStages.func7(0x7?, 0x0?, 0x2ddfa38?, {0x2db93a8?, 0xc000db0420?}, {{0x2dec820?, 0xc000d30a80?}, {0x0?, 0x0?}}, {0x2dd2860, ...})
xlayer-rpc              | 	github.com/ledgerwatch/erigon/zk/stages/stages.go:275 +0x9d
xlayer-rpc              | github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc000db0420, 0xc000903c20, {0x2dd3cb8?, 0xc000c44900}, {{0x2dec820?, 0xc000d30a80?}, {0x0?, 0x0?}}, 0xe0?, 0x0)
xlayer-rpc              | 	github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:513 +0x197
xlayer-rpc              | github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc000db0420, {0x2dd3cb8, 0xc000c44900}, {{0x2dec820?, 0xc000d30a80?}, {0x0?, 0x0?}}, 0x74?)
xlayer-rpc              | 	github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:383 +0x2b6
xlayer-rpc              | github.com/ledgerwatch/erigon/turbo/stages.StageLoopIteration({0x2dc34d0, 0xc000c188c0}, {0x2dd3cb8, 0xc000c44900}, {{0x0?, 0x0?}, {0x0?, 0x0?}}, 0xc000db0420, 0x0, ...)
xlayer-rpc              | 	github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:154 +0x41b
xlayer-rpc              | github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x2dc34d0, 0xc000c188c0}, {0x2dd3cb8, 0xc000c44900}, 0x4675fc?, 0xc001080600, 0x2df04c8?, 0x0, {0x2dd2860, 0xc001839800}, ...)
xlayer-rpc              | 	github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:73 +0x187
xlayer-rpc              | created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start in goroutine 1
xlayer-rpc              | 	github.com/ledgerwatch/erigon/eth/backend.go:1895 +0x6b1
xlayer-rpc              | [INFO] [11-08|10:13:14.437] zjg,Stopping data stream client 192.168.80.16:55310 
xlayer-rpc              | 2024-11-08T10:13:14.437Z	INFO	client/commands.go:90	zjg, 192.168.80.16:55310 Sent command 2, local:192.168.80.16:55310	{"pid": 1, "version": "1212120xff"}
xlayer-rpc              | [INFO] [11-08|10:13:14.437] [3/15 Batches] Reading blocks from the datastream. 
xlayer-rpc              | [INFO] [11-08|10:13:14.437] [3/15 Batches] Started downloading L2Blocks routine ID: 116900 

```

**Comment by ToniRamirezM** [comment]
I think this issue should be open in [CKD-Erigon repo](https://github.com/0xPolygon/zkevm-data-streamer/issues/153) as it is result of how it uses the data streamer library.
